#!/bin/bash

set -e

TEMPLATE_DIR=${0%/*/*}/lib/node_modules/${0##*/}/template

if [ -z "$1" ]; then
  npx create-react-app --help | sed 's/create-react-app/create-react-dapp/'
  exit 1
fi

APP_NAME=$1

echo '********** 1. CREATE REACT APP $@'
echo
npx create-react-app $@
echo '********** DONE CREATING REACT APP ***********'
echo '**********************************************'
echo
echo '********** 2. CREATING DAPP LAYER ************'
echo
echo Template Source: $TEMPLATE_DIR
echo App Destination `pwd`/$APP_NAME/

## / files
mv $TEMPLATE_DIR/.flowconfig  $APP_NAME/
mv $TEMPLATE_DIR/.gitignore  $APP_NAME/
node $TEMPLATE_DIR/../scripts/merge_package.js $TEMPLATE_DIR/ `pwd`/$APP_NAME/
mv $APP_NAME/README.md $APP_NAME/REACT.md
mv $TEMPLATE_DIR/TEMPLATE.md  $APP_NAME/README.md

## /dapp
mv $TEMPLATE_DIR/dapp $APP_NAME

## /public
mv $TEMPLATE_DIR/public/favicon.ico $APP_NAME/public
mv $TEMPLATE_DIR/public/index.html $APP_NAME/public/index.html
sed 's/App/dApp/g' $APP_NAME/public/manifest.json > $APP_NAME/public/_manifest.json
mv $APP_NAME/public/_manifest.json $APP_NAME/public/manifest.json

## /src
rm $APP_NAME/src/App.* $APP_NAME/src/index.*
mv $TEMPLATE_DIR/src/*  $APP_NAME/src/


