#!/bin/bash

PACKAGE_DIR=${0%/*/*}

if [ -z "$1" ]; then
  npx create-react-app --help | sed 's/create-react-app/create-react-dapp/'
  exit 1
fi

PACKAGE_NAME=$1

echo '********** 1. CREATE REACT APP $@'
echo
npx create-react-app $@
echo '********** DONE CREATING REACT APP ***********'
echo '**********************************************'

echo '********** 2. CREATING DAPP LAYER ************'

echo command $0
echo local_variables:
compgen -v
echo environment:
env | sort
echo CWD
pwd

mv $PACKAGE_DIR/node_modules/$PACKAGE_NAME/dapp $1/.
